### PR TITLE
JW-1269 Remove vendor code from contrail-windows-docker-driver and use dependency manager

### PR DESCRIPTION
**Pull request by kaweue**

### CODE REVIEW

**Review by m-kostrzewa — APPROVED** [review]
I'm wondering whether we need to update Attributions.txt because a URL changed or something?

**Comment by kaweue** [comment]
@m-kostrzewa I was thinking about it. I would like to do this in separate pull request. I have a script which should generate this Attributions.txt

**Comment by m-kostrzewa** [comment]
@PawelMarchewkaCodiLime kk

**Comment by m-kostrzewa** [comment]
@PawelMarchewkaCodiLime actually, could you fix the name of this PR? `JW` letters should be both capital

**Review by jablonskim — APPROVED** [review]

**Pull request merged**
