### PR TITLE
JW-309 Update and fix dependencies

### PR DESCRIPTION
**Pull request by m-kostrzewa**
Update vendors so that we don't have to pull anything in CI.

Update docker/docker vendor.

Update docker.NetworkInspect calls to properly use new parameter (they added "verbose bool" param https://github.com/docker/docker/blob/master/client/network_inspect.go#L15)

### CODE REVIEW

**Comment by m-kostrzewa** [comment]
"Update vendors" commit doesn't have to be reviewed

**Comment by m-kostrzewa** [comment]
Retest this please

**Comment by m-kostrzewa** [comment]
Retest this please

**Comment by m-kostrzewa** [comment]
Retest this please

**Comment by m-kostrzewa** [comment]
Retest this please

**Review by mclapinski — APPROVED** [review]

**Pull request merged**
