### PR TITLE
Remove unused CI files

### PR DESCRIPTION
**Pull request by m-kostrzewa**
Remove unused powershell scripts since we transitioned to Jenkins.

### CODE REVIEW

**Comment by m-kostrzewa** [comment]
Retest this please

**Comment by m-kostrzewa** [comment]
Retest this please

**Comment by m-kostrzewa** [comment]
Retest this please

**Comment by m-kostrzewa** [comment]
Retest this please

**Comment by m-kostrzewa** [comment]
Retest this please

**Comment by renkam** [comment]
Retest this please

**Comment by renkam** [comment]
Retest this please

**Comment by renkam** [comment]
Retest this please

**Comment by renkam** [comment]
Retest this please

**Comment by m-kostrzewa** [comment]
Retest this please

**Comment by m-kostrzewa** [comment]
Retest this please

**Comment by m-kostrzewa** [comment]
Retest this please

**Comment by m-kostrzewa** [comment]
Retest this please

**Review by sodar — APPROVED** [review]

**Pull request merged**
