### PR TITLE
JW-230 Powershell noninteractive mode

### PR DESCRIPTION
**Pull request by m-kostrzewa**
Makes it so that when calling Powershell scripts, it doesn't print stuff like "Are you sure you want to delete HNS network? Y/N"

### CODE REVIEW

**Comment by m-kostrzewa** [comment]
Retest this please

**Review by mclapinski — APPROVED** [review]

**Comment by m-kostrzewa** [comment]
Retest this please

**Comment by m-kostrzewa** [comment]
Retest this please

**Comment by m-kostrzewa** [comment]
Retest this please

**Pull request merged**
