### PR TITLE
Generate junit test reports.

### PR DESCRIPTION
**Pull request by m-kostrzewa**
Output .xmls are in the same directories as the package sources

### CODE REVIEW

**Comment by sawicki-maciej** [comment]
Retest this please

**Comment by sawicki-maciej** [comment]
Retest this please

**Comment by sawicki-maciej** [comment]
Retest this please

**Comment by sawicki-maciej** [comment]
Retest this please

**Comment by sawicki-maciej** [comment]
Retest this please

**Comment by sawicki-maciej** [comment]
Retest this please

**Comment by sawicki-maciej** [comment]
Retest this please

**Comment by sawicki-maciej** [comment]
LGFM

**Review by sawicki-maciej — APPROVED** [review]
LGFM

**Comment by sawicki-maciej** [comment]
Retest this please

**Comment by sawicki-maciej** [comment]
Retest this please

**Comment by m-kostrzewa** [comment]
Retest this please

**Comment by sawicki-maciej** [comment]
Retest this please

**Comment by sawicki-maciej** [comment]
Retest this please

**Comment by m-kostrzewa** [comment]
@viroos i merged this branch I don't think jenkins will test it anymore

**Pull request merged**
